name: Run tests
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # tests supported django versions against python versions django officially support plus one higher
        include:
          - { "django-version": "2.2", "python-version": "3.8" }
          - { "django-version": "2.2", "python-version": "3.9" }
          - { "django-version": "3.0", "python-version": "3.8" }
          - { "django-version": "3.0", "python-version": "3.9" }
          - { "django-version": "3.1", "python-version": "3.8" }
          - { "django-version": "3.1", "python-version": "3.9" }
          - { "django-version": "3.2", "python-version": "3.8" }
          - { "django-version": "3.2", "python-version": "3.9" }
          - { "django-version": "3.2", "python-version": "3.10" }
          - { "django-version": "4.0", "python-version": "3.8" }
          - { "django-version": "4.0", "python-version": "3.9" }
          - { "django-version": "4.0", "python-version": "3.10" }
          - { "django-version": "4.0", "python-version": "3.11" }
          - { "django-version": "4.1", "python-version": "3.8" }
          - { "django-version": "4.1", "python-version": "3.9" }
          - { "django-version": "4.1", "python-version": "3.10" }
          - { "django-version": "4.1", "python-version": "3.11" }
          - { "django-version": "4.2", "python-version": "3.8" }
          - { "django-version": "4.2", "python-version": "3.9" }
          - { "django-version": "4.2", "python-version": "3.10" }
          - { "django-version": "4.2", "python-version": "3.11" }
          - { "django-version": "4.2", "python-version": "3.12" }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update setuptools pip and wheel
        run: pip install -U setuptools pip wheel
      - name: Install django
        run: pip install django~=${{ matrix.django-version }}.0
      - name: Install testing requirements
        run: pip install -r requirements-test.txt
      - name: Run tests
        run: |
          pip install --editable .
          python -m tests
